import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
const API_URL=import.meta.env.VITE_API_URL||'http://localhost:5000/api';
type User={id:string;name:string;email:string;role:'admin'|'user'|'viewer'};
type AuthContextType={user:User|null;loading:boolean;login:(email:string,password:string)=>Promise<void>;register:(name:string,email:string,password:string)=>Promise<void>;logout:()=>Promise<void>};
const AuthContext=createContext<AuthContextType|null>(null);
const ACCESS='jervis_access_token',REFRESH='jervis_refresh_token';
export const getAccessToken=()=>localStorage.getItem(ACCESS);
function save(data:{accessToken:string;refreshToken:string}){localStorage.setItem(ACCESS,data.accessToken);localStorage.setItem(REFRESH,data.refreshToken);}
export async function refreshAccessToken(){const refreshToken=localStorage.getItem(REFRESH);if(!refreshToken)return null;const r=await fetch(`${API_URL}/auth/refresh`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refreshToken})});if(!r.ok){localStorage.removeItem(ACCESS);localStorage.removeItem(REFRESH);return null;}const j=await r.json();save(j.data);return j.data.accessToken as string;}
export async function authFetch(input:RequestInfo|URL,init:RequestInit={}){const headers=new Headers(init.headers);const token=getAccessToken();if(token)headers.set('Authorization',`Bearer ${token}`);let r=await fetch(input,{...init,headers});if(r.status===401&&localStorage.getItem(REFRESH)){const next=await refreshAccessToken();if(next){headers.set('Authorization',`Bearer ${next}`);r=await fetch(input,{...init,headers});}}return r;}
export function AuthProvider({children}:{children:ReactNode}){const[user,setUser]=useState<User|null>(null);const[loading,setLoading]=useState(true);useEffect(()=>{(async()=>{try{const r=await authFetch(`${API_URL}/auth/me`);if(r.ok)setUser((await r.json()).data);}finally{setLoading(false);}})();},[]);async function submit(path:string,body:object){const r=await fetch(`${API_URL}/auth/${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error?.message||'Authentication failed');save(j.data);setUser(j.data.user);}const value=useMemo(()=>({user,loading,login:(email:string,password:string)=>submit('login',{email,password}),register:(name:string,email:string,password:string)=>submit('register',{name,email,password}),logout:async()=>{const refreshToken=localStorage.getItem(REFRESH);await fetch(`${API_URL}/auth/logout`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refreshToken})}).catch(()=>{});localStorage.clear();setUser(null);}}),[user,loading]);return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>}
export function useAuth(){const c=useContext(AuthContext);if(!c)throw new Error('useAuth outside AuthProvider');return c;}
